WebDriverAgentMac/WebDriverAgentLib/Routing/FBElementCache.m

Actually, aligned it with Android's UIA2 implementation at https://github.com/appium/appium-uiautomator2-server/pull/392

chore: Limit the maximum size of the elements cache

---

WebDriverAgentMac/WebDriverAgentLib/Routing/FBWebServer.m

https://github.com/appium/appium-mac2-driver/issues/18

chore: Print out the ServerURL

---

lib/driver.js

Fixes https://github.com/appium/appium-mac2-driver/issues/29

fix: Add the missing settings handler

---

WebDriverAgentMac/WebDriverAgentLib/Routing/FBElementCache.m

Now storing and retrieval of elements from cache is done in O(1), which is supposed to be like

refactor: Simplify elements caching logic

---

README.md

It didn't work when I tried it.

chore: fix python sample in README

---

README.md
WebDriverAgentMac/WebDriverAgentLib/Commands/FBElementCommands.m
WebDriverAgentMac/WebDriverAgentLib/Utilities/AMKeyboardUtils.h
WebDriverAgentMac/WebDriverAgentLib/Utilities/AMKeyboardUtils.m
WebDriverAgentMac/WebDriverAgentMac.xcodeproj/project.pbxproj

https://github.com/appium/appium-mac2-driver/issues/59

feat: Add a possibility to provide key names

---

README.md
WebDriverAgentMac/WebDriverAgentLib/Categories/XCUIElement+AMAttributes.m
WebDriverAgentMac/WebDriverAgentLib/Utilities/FBElementUtils.m

https://github.com/appium/appium-mac2-driver/issues/64

feat: Add 'hittable' element attribute

---

WebDriverAgentMac/WebDriverAgentLib/Routing/FBWebServer.m
WebDriverAgentMac/WebDriverAgentRunner/WebDriverAgentRunner.m
lib/wda-mac.js
package.json

Related to https://github.com/appium/appium-mac2-driver/issues/72

feat: Try to terminate an obsolete server instance gracefully before throwing an exception

---

README.md
lib/commands/applescript.js

https://github.com/appium/appium-mac2-driver/issues/88

feat: Add a possibility to change scripting language

---

WebDriverAgentMac/WebDriverAgentRunner/WebDriverAgentRunner.m

Also increased the default timeout to 24 hours

chore: Ignore test failures

---

test/functional/basic-e2e-specs.js
test/functional/interaction-e2e-specs.js

wdio requires executeScript args to be an array

fix: Update executeScript args format

---

README.md

https://github.com/appium/appium-mac2-driver/issues/104#issuecomment-1097245076

docs: address automationmodetool

---

WebDriverAgentMac/WebDriverAgentLib/Commands/FBElementCommands.m
WebDriverAgentMac/WebDriverAgentLib/Commands/FBScreenshotCommands.m
WebDriverAgentMac/WebDriverAgentLib/Utilities/AMSnapshotUtils.m

Similar to https://github.com/appium/WebDriverAgent/pull/627

fix: Enforce usage of base64 RFC4648 encoder

---

WebDriverAgentMac/WebDriverAgentLib/Categories/XCUIElementQuery+AMHelpers.m
WebDriverAgentMac/WebDriverAgentLib/Commands/FBSessionCommands.m
WebDriverAgentMac/WebDriverAgentLib/Routing/FBSession.h
WebDriverAgentMac/WebDriverAgentLib/Utilities/FBConfiguration.h
WebDriverAgentMac/WebDriverAgentLib/Utilities/FBConfiguration.m

Related to https://github.com/appium/appium/pull/17727

refactor: Reset session-specific settings on its startup

---

lib/driver.js

Related to https://github.com/appium/appium-mac2-driver/issues/172#issuecomment-1379616241

fix: Proxy getStatus call to WDA

---

package.json

From https://github.com/appium/appium-mac2-driver/issues/184

ci: Typo in e2e-test

---

WebDriverAgentMac/WebDriverAgentLib/Commands/AMActionCommands.m

Related to https://github.com/appium/appium-mac2-driver/issues/189

chore: Add dummy implementation of releaseActions API

---

README.md

Same as https://github.com/appium/appium-xcuitest-driver/pull/2295/

docs: Add the description of the modifierFlags argument

---

lib/driver.js
lib/wda-mac.js

https://github.com/appium/appium/pull/21021

fix: Accept reqBasePath proxy option

---

README.md
WebDriverAgentMac/IntegrationTests/AMPasteboardTests.m
WebDriverAgentMac/WebDriverAgentLib/Commands/FBCustomCommands.m
WebDriverAgentMac/WebDriverAgentLib/Utilities/AMPasteboard.h
WebDriverAgentMac/WebDriverAgentLib/Utilities/AMPasteboard.m
WebDriverAgentMac/WebDriverAgentMac.xcodeproj/project.pbxproj
lib/commands/clipboard.ts
lib/driver.js
lib/execute-method-map.ts

https://github.com/appium/appium-mac2-driver/issues/345

feat: Add clipboard support
